### ISSUE TITLE
suspected tree format error

### ISSUE THREAD

**Issue by dw974** [dhelekal/CaveDive#12]
Hi. Great program.
I get the following error when attempting to run "run_expansion_inference" on the attached file [tree.txt](https://github.com/dhelekal/CaveDive/files/9744048/tree.txt):

Error in clade_tip_recursion(index_lo, index_hi - count_right, next_v[1],  : 
  index error

I have already run 'makenodelabels', following the instructions from the other raised issues. I suspect this is some other tree-format issue.
The tree was made using IQtree2. Any ideas?

**Comment by dhelekal** [comment]
Hi, I had a quick look at the tree and I think there are two main issues. The first problem is that the tree is not binary (i.e. it has multiple collisions).  Our model can only handle binary trees.
 The second problem is that even if the tree was binary, the node labels aren't unique. I assume this is related to how makeNodeLabel handles non-binary trees if called with other than default arguments.
I think the main question is why exactly does the tree have multiple collisions. Even if the multiple collisions were split up into 0 length binary branching, it would still not be compatible with CaveDive. Has the tree been dated at all?

**Comment by dw974** [comment]
Wow. Thanks for the really quick reply.
If I've understood the format, then I think you can make the node labels unique using makeNodeLabel even on multifurcating trees (which I have done in the attached version)
[tree.txt](https://github.com/dhelekal/CaveDive/files/9745673/tree.txt)

But this gives the same error. 

So this is an IQTree timetree format issue by the looks of things. The software does seem to have a few slightly odd things about it that could be creating the multifurcating issue.
One thing is that it removes unique sequences at the start and then puts them back in again (on a multifurcating node) at the end - not sure how it then deals with dating exactly. We can undo this behaviour using the "--keep-ident" command, which is missing from the documentation in the newer versions...
I found something in the depths of the google groups discussion page that suggested you might be able to impose a minimum branch length, but this doesn't seem to stop it from making multifurcating nodes.
I can't see anything immediately that would allow me to impose bifurcation in the timetree output... so I'll have to approach the developers.
Thanks again for the speedy response.

**Comment by dhelekal** [comment]
I looked at the tree again. I think the main issue is  that this is not a dated phylogeny, given that the scale of the branch lengths is of order 1e-3 to 1e-6. I'm not familiar with IQTree, presumably there is an option for it to date the tree as well. Other than that you could convert the tree to a binary tree via `multi2di` from `ape` and then generate a time tree using some other package for dating phylogenies.

**Comment by dhelekal** [comment]
Closing issue as this seems to be a data issue.

**Comment by dhelekal** [comment]
Closing issue as this seems to be a data issue.
