### ISSUE TITLE
Error while runnig the example data from the analyse_tree_s2.rmd

### ISSUE THREAD

**Issue by rorycave** [dhelekal/CaveDive#13]
I tried running the example data in the published paper of GPSC9 Lineage and I get this error when i run this command:

 expansions <- run_expansion_inference(tree, priors, 1, n_it=n_it, thinning=thinning)

Error in nodes$times[edges$node.child[curr_br]] > div.times_upd && nodes$times[edges$node.parent[curr_br]] <  : 
  'length = 552' in coercion to 'logical(1)'

**Comment by dhelekal** [comment]
I can definitely reproduce this on other data. There's probably a conflict with a new version of a an imported package somewhere.

**Comment by rorycave** [comment]
I'm not 100% sure but I think it is due to new versions of R. It worked for me on version 4.2.3 but not version 4.3.3.

**Comment by anabuiatte** [comment]
Hi!
I also tried to run the examples mentioned, and I got the same error when I ran the "run_expansion_inference" command. Any solutions? I couldn't run it in R version 4.3.2, nor in version 4.4.0.  Thanks!

**Comment by xavierdidelot** [comment]
I have just pushed a small change which I think should fix this issue, could you please confirm?

**Comment by anabuiatte** [comment]
Hi Xavier!
It's working now, thank you so much! 😃

**Comment by dhelekal** [comment]
Thanks a lot Xavier, I was struggling to find what broke there with newer R versions

**Comment by xavierdidelot** [comment]
No worries, I'm glad it worked!
