### ISSUE TITLE
how to analysis the dated phylogeny from beast and treedater

### ISSUE THREAD

**Issue by Spatial-R** [dhelekal/CaveDive#6]
Dear, thanks for your nice package! When using the `run_expansion_inference` function on a dated phylogeny from beast (using the read.beast function in the treeio), an error comes:
 Error in if (nodes.df$is_tip[id]){: argument is of length zero. 

I check the dated phylogeny used in the vignettes, it seems that the phylogeny has the node label. Is there any example which inference the clonal expansions  based on the beast or treedater? Thanks!

**Comment by dhelekal** [comment]
Hi, thank you for bringing this to my attention. I think this might actually be a bug or some weird edge case going on. Could you please provide a minimal working example that replicates this issue?

**Comment by Spatial-R** [comment]
Thanks for your timely response. The tree data is [here](https://github.com/Spatial-R/Data-visualization-in-public-health/blob/master/example.tree).

**Comment by dhelekal** [comment]
Hi, the tree you sent only has tip labels and does not seem to include node labels. Node labels can be generated using the `ape` function `makeNodeLabel`. Once the node labels are present the error goes away. 
The error you got should've been a bit more helpful, as the missing labels were supposed to have been detected earlier during an input validity check, except they didnt

**Comment by dhelekal** [comment]
#7
